### ISSUE TITLE
Mention of "network" on /update_ip.html

### ISSUE THREAD

**Issue by S-Coyle** [krishnaIndia/crust_dashboard#43]
Not a priority bug (IMO), but the word "network" has been explicitly removed from elsewhere in marketing communications, URLs and the dashboard, so ideally wouldn't be mentioned here either.

![image](https://user-images.githubusercontent.com/37112040/46906666-045d3600-ceff-11e8-9250-df057e8eedc1.png)

**Comment by ravinderjangra** [comment]
@S-Coyle what should be mentioned here? 
Will "SAFE - CRUST Test" be fine? or just "CRUST Test"
