### ISSUE TITLE
ipapi monthly quota used - upgrade required

### ISSUE THREAD

**Issue by S-Coyle** [krishnaIndia/crust_dashboard#45]
{ "geo_info" : { "error" : true, "message" : "Upgrade your plan @ https://ipapi.co/", "reason" : "RateLimited" }

**Comment by ravinderjangra** [comment]
@S-Coyle we are using the free version of the ipapi service. we need to buy this Victoria and Nadia already know about this. I am updating the code also so that we don't expose internal logs in the worst case scenario.

**Comment by S-Coyle** [comment]
@krishnaIndia @ravinderjangra  just wanted to confirm what the end result of this was, have we signed up for a particular requests amount per month? What's the amount? Couldn't see a finalised decision in Slack

**Comment by S-Coyle** [comment]
Discussed with Krishna today and confirmed that we have signed up for ipapi.co 60,000 requests per month
