### ISSUE TITLE
Wipe results from server / database if required 

### ISSUE THREAD

**Issue by nadiaburborough** [krishnaIndia/crust_dashboard#65]
Need to decide whether to keep the results each iteration

**Comment by S-Coyle** [comment]
@nadiaburborough something to keep in mind here is that the Dashboard stats may not match the BE guys stats any time we restart the server and proxy, or wipe results from just 1 area, e.g. the mongodb. For example, I have just restarted the server & proxy now and the BE guys will be looking at a new clear log file from now on.
Just discussed this with Nikita and he said it doesn't really affect them - he will just change his program to gather stats to include 2 log files...
Hope that makes sense, if not pop down and I'll try to explain better

**Comment by S-Coyle** [comment]
Confirmed with marketing that this is not required - leave office test data in
